#spring:
#  datasource:
#   username: root
#   password: 123456
#   url: jdbc:mysql://localhost:3306/User_Service
#   driver-class-name: com.mysql.cj.jdbc.Driver

# jpa:
#   show-sql: true
#   hibernate:
#     ddl-auto: update
#   properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect